version: '3.9'

services:
  app:
    build: .
    container_name: cardsbot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - CRYPTO_TOKEN=${CRYPTO_TOKEN}
      - FLYER_TOKEN=${FLYER_TOKEN}
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network
    volumes:
      - .:/app
    restart: always
networks:
  app_network:
    driver: bridge
